version: '3.8'

services:
  app:
    image: companysearch
    container_name: companysearch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticsearch
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/company
      - SPRING_DATASOURCE_USERNAME=company_user
      - SPRING_DATASOURCE_PASSWORD=company_password
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200

  db:
    image: postgres:16.0
    container_name: postgres_db
    environment:
      POSTGRES_DB: company
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_password
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044" # Logstash Beats input (e.g., Filebeat)
      - "5001:5000" # Logstash TCP input
      - "9600:9600" # Logstash monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g